version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=kltn_database
      - MYSQL_ROOT_PASSWORD=anhquan1
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - REACT_URL=http://localhost/
      #- DB_HOST=host.docker.internal
    ports:
      - 2000:2000
    expose:
      - 2000

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../tuyen-sinh-dai-hoc/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
