version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=kltn_database
      - MYSQL_ROOT_PASSWORD=anhquan1
    ports:
      - '3307:3306'
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 10s

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - REACT_URL=http://localhost/
      #- DB_HOST=host.docker.internal
    expose:
      - 2000
    depends_on:
      database-mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:2000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:1.23.3
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80
    volumes:
      - ../tuyen-sinh-dai-hoc/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

